Repository theelliotm/netbox-sd-access, pull requests merged in 2024-07, with the labels that each got.

#23 Virtual networks branch
  .devcontainer/Dockerfile-plugin_dev
  netbox_sd_access/api/serializers.py
  netbox_sd_access/api/urls.py
  netbox_sd_access/api/views.py
  netbox_sd_access/filtersets.py
  netbox_sd_access/forms.py
  netbox_sd_access/graphql/filters.py
  netbox_sd_access/graphql/schema.py
  netbox_sd_access/graphql/types.py
  netbox_sd_access/migrations/0009_virtualnetwork.py
  netbox_sd_access/models.py
  netbox_sd_access/navigation.py
  netbox_sd_access/tables.py
  netbox_sd_access/templates/netbox_sd_access/virtualnetwork.html
  netbox_sd_access/urls.py
  netbox_sd_access/views.py
Labels: enhancement

#27 Device bulk branch
  netbox_sd_access/forms.py
  netbox_sd_access/navigation.py
  netbox_sd_access/urls.py
  netbox_sd_access/views.py
Labels: enhancement

#32 Adds tests for all model types
  README.md
  netbox_sd_access/api/serializers.py
  netbox_sd_access/forms.py
  netbox_sd_access/graphql/__init__.py
  netbox_sd_access/graphql/schema.py
  netbox_sd_access/graphql/types.py
  netbox_sd_access/migrations/0010_alter_virtualnetwork_vrf.py
  netbox_sd_access/models.py
  netbox_sd_access/navigation.py
  netbox_sd_access/tests/__init__.py
  netbox_sd_access/tests/test_fabric_site.py
  netbox_sd_access/tests/test_ip_pool.py
  netbox_sd_access/tests/test_ip_transit.py
  netbox_sd_access/tests/test_sd_transit.py
  netbox_sd_access/tests/test_sda_device.py
  netbox_sd_access/tests/test_virtual_network.py
  netbox_sd_access/urls.py
  netbox_sd_access/views.py
  tests/test_netbox_sd_access.py
Labels: tests

#36 Comments for fabric site
  netbox_sd_access/api/serializers.py
  netbox_sd_access/filtersets.py
  netbox_sd_access/forms.py
  netbox_sd_access/graphql/types.py
  netbox_sd_access/migrations/0012_fabricsite_comments.py
  netbox_sd_access/migrations/0013_ippool_comments.py
  netbox_sd_access/models.py
  netbox_sd_access/templates/netbox_sd_access/ippool.html
  netbox_sd_access/templates/netbox_sd_access/virtualnetwork.html
Labels: enhancement

#37 V0.1 documentation
  netbox_sd_access/api/serializers.py
  netbox_sd_access/api/views.py
  netbox_sd_access/filtersets.py
  netbox_sd_access/forms.py
  netbox_sd_access/graphql/types.py
  netbox_sd_access/migrations/0014_delete_sdaccess.py
  netbox_sd_access/models.py
  netbox_sd_access/navigation.py
  netbox_sd_access/tables.py
  netbox_sd_access/templates/netbox_sd_access/sd-access.html
  netbox_sd_access/tests/test_fabric_site.py
  netbox_sd_access/tests/test_ip_pool.py
  netbox_sd_access/tests/test_ip_transit.py
  netbox_sd_access/tests/test_sd_transit.py
  netbox_sd_access/tests/test_sda_device.py
  netbox_sd_access/tests/test_virtual_network.py
  netbox_sd_access/urls.py
  netbox_sd_access/views.py
Labels: documentation
